// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: habits.sql

package sqlite3Storage

import (
	"context"
	"database/sql"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (user_id, name, description, colour, ` + "`" + `index` + "`" + `) VALUES (?, ?, ?, ?, ?) RETURNING id, user_id, name, description, created_at, updated_at, colour, ` + "`" + `index` + "`" + `, active
`

type CreateHabitParams struct {
	UserID      int64
	Name        string
	Description sql.NullString
	Colour      string
	Index       int64
}

// Create a new habit
func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRowContext(ctx, createHabit,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Colour,
		arg.Index,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Colour,
		&i.Index,
		&i.Active,
	)
	return i, err
}

const deleteHabit = `-- name: DeleteHabit :one
DELETE FROM habits WHERE id = ? RETURNING id, user_id, name, description, created_at, updated_at, colour, ` + "`" + `index` + "`" + `, active
`

// Delete a habit by ID
func (q *Queries) DeleteHabit(ctx context.Context, id int64) (Habit, error) {
	row := q.db.QueryRowContext(ctx, deleteHabit, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Colour,
		&i.Index,
		&i.Active,
	)
	return i, err
}

const getHabit = `-- name: GetHabit :one
SELECT id, user_id, name, description, created_at, updated_at, colour, ` + "`" + `index` + "`" + `, active FROM habits WHERE id = ?
`

// Retrieve a habit by ID
func (q *Queries) GetHabit(ctx context.Context, id int64) (Habit, error) {
	row := q.db.QueryRowContext(ctx, getHabit, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Colour,
		&i.Index,
		&i.Active,
	)
	return i, err
}

const getHabits = `-- name: GetHabits :many
SELECT id, user_id, name, description, created_at, updated_at, colour, ` + "`" + `index` + "`" + `, active FROM habits WHERE user_id = ?
`

// Retrieve all habits for a user
func (q *Queries) GetHabits(ctx context.Context, userID int64) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, getHabits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Colour,
			&i.Index,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHabit = `-- name: UpdateHabit :one
UPDATE habits SET name = ?, description = ?, colour = ?, ` + "`" + `index` + "`" + ` = ?, updated_at = ? WHERE id = ? RETURNING id, user_id, name, description, created_at, updated_at, colour, ` + "`" + `index` + "`" + `, active
`

type UpdateHabitParams struct {
	Name        string
	Description sql.NullString
	Colour      string
	Index       int64
	UpdatedAt   string
	ID          int64
}

// Update a habit by ID
func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) (Habit, error) {
	row := q.db.QueryRowContext(ctx, updateHabit,
		arg.Name,
		arg.Description,
		arg.Colour,
		arg.Index,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Colour,
		&i.Index,
		&i.Active,
	)
	return i, err
}
