// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlite3Storage

import (
	"database/sql"
)

type Habit struct {
	ID          int64
	UserID      int64
	Name        string
	Description sql.NullString
	CreatedAt   string
	UpdatedAt   string
}

type HabitEntry struct {
	ID        int64
	HabitID   int64
	Date      string
	CreatedAt string
	UpdatedAt string
}

type User struct {
	ID        int64
	Name      string
	CreatedAt string
	UpdatedAt string
}
